### PR TITLE
Do not generate config for fake commands and useless arguments

### LINKED ISSUE #56: [Bug]: Check Command no-help is generated
### Please try to fill out as much of the information below as you can. Thank you!

- [x] Yes, I've searched similar issues on GitHub and didn't find any.

### Which version contains the bug?

_No response_

### Describe the bug

When using the "dump-config" option there's a command "system_basics_no-help" generated, as I would like to just write the whole output after the update into the command file. I think this should be omitted. 

### How to recreate the bug?

check_system_basics --dump-icinga2-config

### PR DESCRIPTION
**Pull request by RincewindsHat**
fixes #56

### CODE REVIEW

File: internal/common/config/icinga2Config.go [hunk 1]
```diff
@@ -30,7 +30,9 @@ func GenerateIcinga2Config(cmd *cobra.Command, commandName, executableName strin
 	ccaFlags = make([]icingadsl.CheckCommandArgument, 0)
 
 	flags.VisitAll(func(foo *pflag.Flag) {
-		_ = GenerateIcinga2CheckCommandArgument(foo, &ccaFlags)
+		if foo.Name != "help" && foo.Name != "debug" {
```
Comment (martialblog) [inline internal/common/config/icinga2Config.go:33]: Should we replace the name `foo`?

Comment (RincewindsHat) [reply internal/common/config/icinga2Config.go]: done

**Review by martialblog — APPROVED** [review]
